default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vista-platform_development

test:
  <<: *default
  database: vista-platform_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *default
  database: vista-platform_staging

production:
  <<: *default
  database: vista-platform_production
  username: vista-platform
  password: <%= ENV['VISTA-PLATFORM_DATABASE_PASSWORD'] %>
