default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vista-platform_development

test:
  <<: *default
  database: vista-platform_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *default
  database: d82bj1g12vavj4
  username: npnejimqkgxbni
  password: 838a59b47fc65dff8855d4d8dd6b3d5161aa8764821d96d70a8267a1990dfe2d



production:
  <<: *default
  database: vista-platform_production
  username: vista-platform
  password: <%= ENV['VISTA-PLATFORM_DATABASE_PASSWORD'] %>
